### ISSUE TITLE
Quality of Wallpapers and Autostart

### ISSUE THREAD

**Issue by KR4U7H3R** [Bnyro/WallYou#81] opened 2023-03-31 11:55 UTC
### Steps to reproduce

**First issue**

1. Apply an Wallpaper (in this case from local storage)

**Second issue**

1. Activate Autostart
2. Deactivate Battery Saver for App
3. Restart Phone (by planned restart)

### Expected behavior

**First issue**

- Quality should be the same as in Gallery App

**Second issue**

- Autostart should work and wallpaper change every 1h

### Actual behavior

**First issue**

- Quality is lower as in Gallery App (Aves libre)
![Screenshot_2023-03-30-11-05-16-268_com saggitt omega-edit](https://user-images.githubusercontent.com/117851447/229111521-e07c4d9b-8c55-42e2-ad65-ebc858694934.jpg)
WallYou
![Screenshot_2023-03-30-11-06-05-761_com saggitt omega-edit](https://user-images.githubusercontent.com/117851447/229111527-8f324fd1-f206-465a-8947-603e0fa0a967.jpg)
Aves Libre
![Screenshot_2023-03-31-13-25-48-286_com saggitt omega~2](https://user-images.githubusercontent.com/117851447/229111532-fc039565-4896-49fb-8d7f-04b074f9f44c.jpg)
WallYou
![Screenshot_2023-03-31-13-26-06-451_com saggitt omega~2](https://user-images.githubusercontent.com/117851447/229111537-0c6327ef-29af-4b7d-a8d3-2156d36479ba.jpg)
Aves Libre

The first two pictures is the problem which I am referring to. The WallYou pictures looks blurrier and pixilated.
The second two pictures show an other wallpaper, and show that the result is more pixilated.
See also the (new) pictures I added in #64.

**Second issue**

- The app has to be started manually to work. Not a big problem, but maybe you have experience with this?

### Wall You version

3.3 (17)

### Android version

Android 13

### Other details

As I am using quite a lot of minimalistic wallpapers these problems are often visible. Other wallpapers work fine. I really like your app(s), thanks a lot for your work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-06-07 10:48
Unfortunately I don't have any idea what could cause the wallpaper resolution issue (and I don't aim to do anything about it currently, sorry).
The boot issue should be fixed now.

**Closed** 2023-06-07 10:47 UTC
Labels: bug

**Comment by emavgl** [comment] 2023-12-23 16:27
Hi @Bnyro, I am encountering the same problem with the low quality wallpaper resolution. 

I think that the problem is due to the method `createScaledBitmap` which is used in the [WallpaperHelper](https://github.com/you-apps/WallYou/blob/main/app/src/main/java/com/bnyro/wallpaper/util/WallpaperHelper.kt) class in both cropped and non-cropped version.

According to [this page](https://stackoverflow.com/questions/4821488/bad-image-quality-after-resizing-scaling-bitmap) of Stackoverflow seems to be a common issue with this function.

**Comment by Bnyro** [comment] 2023-12-23 17:39
No, feel free to create a pull request if you tested it to make sure it actually has an impact.

**Comment by emavgl** [comment] 2023-12-24 10:41
I tried on my fork, but unforutnately seem not solving the issue, the quality of the image is significantly bad to me :(
